#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := cryptoauthlib_mbedtls_ecdsa_example

include $(IDF_PATH)/make/project.mk

